In [1]:
import torch

In [13]:
t1 = torch.tensor([[1,1,1],[2,2,2]])
t2 = torch.tensor([[2,2,2],[3,3,3]])
t3 = torch.tensor([[3,3,3],[4,4,4]])

In [14]:
torch.cat((t1,t2,t3),dim=0)

tensor([[1, 1, 1],
        [2, 2, 2],
        [2, 2, 2],
        [3, 3, 3],
        [3, 3, 3],
        [4, 4, 4]])

In [15]:
torch.cat((t1,t2,t3),dim=1)

tensor([[1, 1, 1, 2, 2, 2, 3, 3, 3],
        [2, 2, 2, 3, 3, 3, 4, 4, 4]])

In [16]:
torch.stack((t1,t2,t3),dim=0)

tensor([[[1, 1, 1],
         [2, 2, 2]],

        [[2, 2, 2],
         [3, 3, 3]],

        [[3, 3, 3],
         [4, 4, 4]]])

In [17]:
torch.stack((t1,t2,t3),dim=1)

tensor([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]],

        [[2, 2, 2],
         [3, 3, 3],
         [4, 4, 4]]])

In [18]:
torch.cat((t1.unsqueeze(1),t2.unsqueeze(1),t3.unsqueeze(1)),dim=1)

tensor([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]],

        [[2, 2, 2],
         [3, 3, 3],
         [4, 4, 4]]])