In [2]:
import torch.nn as nn

class Network(nn.Module):
    def __init__(self):
        super(Network,self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=12, kernel_size=5)
        
        self.fc1 = nn.Linear(in_features=12*4*4, out_features=120) #
        self.fc2 = nn.Linear(in_features=120, out_features=60)
        self.out = nn.Linear(in_features=60, out_features=10)
    
    def forward(self, t):
        #t = self.layer(t)
        return t
    
    def __repr__(self):
        return 'Self_defined Net'

In [3]:
network = Network()
network

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)

In [6]:
print(network)

Network(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 12, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=192, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=60, bias=True)
  (out): Linear(in_features=60, out_features=10, bias=True)
)


In [8]:
network.conv1.weight

Parameter containing:
tensor([[[[-0.0968, -0.0276,  0.0140, -0.1945, -0.0282],
          [-0.0695,  0.1996, -0.0541,  0.0345, -0.1800],
          [-0.0306, -0.0358,  0.1870, -0.0755, -0.1772],
          [ 0.1571, -0.1092, -0.0665,  0.1736, -0.1231],
          [-0.0571, -0.0835, -0.0193, -0.1763,  0.0796]]],


        [[[ 0.0720, -0.0834, -0.0050,  0.1000, -0.1020],
          [-0.0572,  0.1722,  0.1553,  0.0385,  0.0528],
          [ 0.1254, -0.0175,  0.0252,  0.1262,  0.1897],
          [ 0.1236, -0.1534,  0.1848, -0.1534,  0.1943],
          [ 0.0217,  0.0265, -0.0334,  0.1719,  0.0742]]],


        [[[-0.0616, -0.1121,  0.1283,  0.0365, -0.0044],
          [ 0.1397, -0.0226, -0.0331,  0.1531, -0.1349],
          [-0.0103,  0.0806,  0.0261, -0.1605,  0.0258],
          [ 0.1014, -0.1967, -0.0637, -0.1501,  0.1137],
          [-0.0661, -0.1296,  0.0959,  0.1667,  0.1184]]],


        [[[-0.0914,  0.1720,  0.1396, -0.1750,  0.1420],
          [-0.0900, -0.1244,  0.0489, -0.0658,  0.1806

In [11]:
import torch
in_features = torch.tensor([1,2,3,4],dtype=torch.float32)

In [13]:
weight_matrix = torch.tensor([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6]
], dtype=torch.float32)

In [16]:
weight_matrix.matmul(in_features)

tensor([30., 40., 50.])

In [27]:
fc = nn.Linear(in_features=4, out_features=3, bias=False)

In [28]:
fc.weight = nn.Parameter(weight_matrix)

In [30]:
fc(in_features)

tensor([30., 40., 50.], grad_fn=<SqueezeBackward3>)

In [46]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
a = torch.from_numpy(a)
b = torch.from_numpy(b)
b

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]], dtype=torch.int32)

In [47]:
a

tensor([1, 2, 3, 4], dtype=torch.int32)

In [51]:
output = a.matmul(b.T)
output

tensor([10, 20, 30], dtype=torch.int32)

In [52]:
output2 = b.matmul(a)
output2

tensor([10, 20, 30], dtype=torch.int32)